name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-13
          - windows-latest
        cpp_arch:
          - x64
        include:
          - os: macos-14 # arm
            cpp_arch: arm64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - uses: pnpm/action-setup@v4

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          vcvarsall: true
          cmake: true
          ninja: true
          python: true
          vcpkg: 608d1dbcd6969679f82b1ca6b89d58939c9b228e
          architecture: ${{ matrix.cpp_arch }}

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run test.lint

      - name: Tests
        run: pnpm test

      - name: Setup Node 12
        uses: actions/setup-node@v4
        with:
          node-version: 12

      - name: Smoke test Node 12
        run: node ./build/main.js --help
