name: CI
on:
  - push
  - pull_request

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 14
          - 20
          - 22
        architecture:
          - x64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # - name: Tests
      #   run: npm test
